### ISSUE TITLE
old libopencm3

### ISSUE THREAD

**Issue by fenugrec** [Galvant/gpibusb-firmware-arm#2]
Hi,
just wondering if you plan on working on this further ?
I've gone ahead and forked this for some local work (mainly updating to more recent libopencm3). 

If you'd test/accept pull requests I will adjust my workflow to make things easily mergeable.
Thanks!

**Comment by scasagrande** [comment]
This project is something that I want to revisit. I never knew that this many people starred a partially-complete project! I don't think I ever tested any of this code with an instrument connected to the micro.

Part of me wants to do this with a cypruss psoc or something. Eventually I'll find time to come back to this, but I need to get a bunch of other stuff (see all the WIP at InstrumentKit) done first. In the mean time I'd be happy to review PRs.

**Comment by fenugrec** [comment]
Thanks for the quick reply.
So I'll definitely be sending in some minor PRs, but other changes I'm planning (skip the UART entirely and implement a USB vendor class) will probably have to remain in a feature branch for a while.
